"""empty message

Revision ID: 013a9ecef29e
Revises: 013e1d0c8f70
Create Date: 2019-10-03 20:15:28.340947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '013a9ecef29e'
down_revision = '013e1d0c8f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('map_or_merge_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('view_right',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('map_or_merge_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_right')
    op.drop_table('share')
    # ### end Alembic commands ###
