"""empty message

Revision ID: 013e1d0c8f70
Revises: 65af394ecc56
Create Date: 2019-09-30 20:10:22.536054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013e1d0c8f70'
down_revision = '65af394ecc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('block_pattern_name_fkey', 'block', type_='foreignkey')
    op.drop_constraint('block_map_id_fkey', 'block', type_='foreignkey')
    op.create_foreign_key(None, 'block', 'pattern', ['pattern_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(None, 'block', 'map', ['map_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('color_rule_block_id_fkey', 'color_rule', type_='foreignkey')
    op.drop_constraint('color_rule_map_id_fkey', 'color_rule', type_='foreignkey')
    op.create_foreign_key(None, 'color_rule', 'block', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'color_rule', 'map', ['map_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('map_user_id_fkey', 'map', type_='foreignkey')
    op.create_foreign_key(None, 'map', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('merge_user_id_fkey', 'merge', type_='foreignkey')
    op.create_foreign_key(None, 'merge', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('merge_map_merge_id_fkey', 'merge_map', type_='foreignkey')
    op.drop_constraint('merge_map_map_id_fkey', 'merge_map', type_='foreignkey')
    op.create_foreign_key(None, 'merge_map', 'map', ['map_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'merge_map', 'merge', ['merge_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pattern_block_pattern_id_fkey', 'pattern_block', type_='foreignkey')
    op.create_foreign_key(None, 'pattern_block', 'pattern', ['pattern_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('real_sense_current_map_id_fkey', 'real_sense', type_='foreignkey')
    op.drop_constraint('real_sense_user_id_fkey', 'real_sense', type_='foreignkey')
    op.create_foreign_key(None, 'real_sense', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'real_sense', 'map', ['current_map_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'real_sense', type_='foreignkey')
    op.drop_constraint(None, 'real_sense', type_='foreignkey')
    op.create_foreign_key('real_sense_user_id_fkey', 'real_sense', 'user', ['user_id'], ['id'])
    op.create_foreign_key('real_sense_current_map_id_fkey', 'real_sense', 'map', ['current_map_id'], ['id'])
    op.drop_constraint(None, 'pattern_block', type_='foreignkey')
    op.create_foreign_key('pattern_block_pattern_id_fkey', 'pattern_block', 'pattern', ['pattern_id'], ['id'])
    op.drop_constraint(None, 'merge_map', type_='foreignkey')
    op.drop_constraint(None, 'merge_map', type_='foreignkey')
    op.create_foreign_key('merge_map_map_id_fkey', 'merge_map', 'map', ['map_id'], ['id'])
    op.create_foreign_key('merge_map_merge_id_fkey', 'merge_map', 'merge', ['merge_id'], ['id'])
    op.drop_constraint(None, 'merge', type_='foreignkey')
    op.create_foreign_key('merge_user_id_fkey', 'merge', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.create_foreign_key('map_user_id_fkey', 'map', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'color_rule', type_='foreignkey')
    op.drop_constraint(None, 'color_rule', type_='foreignkey')
    op.create_foreign_key('color_rule_map_id_fkey', 'color_rule', 'map', ['map_id'], ['id'])
    op.create_foreign_key('color_rule_block_id_fkey', 'color_rule', 'block', ['block_id'], ['id'])
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.create_foreign_key('block_map_id_fkey', 'block', 'map', ['map_id'], ['id'])
    op.create_foreign_key('block_pattern_name_fkey', 'block', 'pattern', ['pattern_name'], ['name'])
    # ### end Alembic commands ###
