"""empty message

Revision ID: 4e83d82b1133
Revises: fa7d67d88d82
Create Date: 2019-09-26 15:24:10.312793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e83d82b1133'
down_revision = 'fa7d67d88d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('map', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'map', 'user', ['user_id'], ['id'])
    op.add_column('merge', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'merge', 'user', ['user_id'], ['id'])
    op.add_column('real_sense', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'real_sense', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'real_sense', type_='foreignkey')
    op.drop_column('real_sense', 'user_id')
    op.drop_constraint(None, 'merge', type_='foreignkey')
    op.drop_column('merge', 'user_id')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_column('map', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
