"""empty message

Revision ID: 65af394ecc56
Revises: 4e83d82b1133
Create Date: 2019-09-26 16:52:58.170317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65af394ecc56'
down_revision = '4e83d82b1133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
