"""empty message

Revision ID: d71989bd35d0
Revises: 013a9ecef29e
Create Date: 2019-10-04 16:03:52.230401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd71989bd35d0'
down_revision = '013a9ecef29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('map_or_merge_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='share_pkey')
    )
    # ### end Alembic commands ###
